# Generated by Django 4.2.4 on 2023-08-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_track_number', models.PositiveIntegerField(editable=False, verbose_name='Порядковый номер')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical_catalog.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Песня в альбоме',
                'verbose_name_plural': 'Песни в альбоме',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('albums', models.ManyToManyField(through='musical_catalog.AlbumSong', to='musical_catalog.album', verbose_name='Альбомы')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.AddField(
            model_name='albumsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musical_catalog.song', verbose_name='Песня'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musical_catalog.artist', verbose_name='Исполнитель'),
        ),
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('album', '_track_number')},
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'artist')},
        ),
    ]
