# Generated by Django 4.2.4 on 2023-08-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musical_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('song', 'album'), name='unique_song_album'),
        ),
    ]
